name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the version of Node.js you need

    - name: Install dependencies
      run: npm install # Or any other package manager command to install dependencies

    - name: Run tests
      run: npm test # Or any other command to run your tests

    - name: Build
      run: npm build # Or any other command to build your code
